#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

gatein_home=${OPENSHIFT_RUNTIME_DIR}gatein/
gatein_git=${gatein_home}gatein-portal-git/
gatein_modules=${gatein_home}jboss-as7-modules/
gatein_built_marker=${gatein_home}built

if [ ! -d "${gatein_home}" ]; then
	mkdir ${gatein_home}
fi

validate_marker

if [ ! -f $gatein_built_marker ]; then
    git clone --depth=1 https://github.com/gatein/gatein-portal.git ${gatein_git}
	cd ${gatein_git}
	git checkout 3.3.0-GA
	cd -

	sed -i -e "s/\${server.name}/jboss-as7/g" ${gatein_git}packaging/jboss-as7/modules/build.xml > /dev/null 2>&1
	mvn -f ${gatein_git}packaging/jboss-as7/modules/pom.xml clean install

	mv ${gatein_git}packaging/jboss-as7/modules/target/jboss-as7-gatein-modules ${gatein_modules}

	#FIXME - edit path
	cp /opt/PATH_TO_JBOSS_AS_INSTALATION/modules/org/jboss/as/web/main/* ${gatein_modules}org/jboss/as/web/main/

	cp -f ${gatein_git}packaging/jboss-as7/pkg/src/main/resources/jboss/modules/org/jboss/as/web/main/module.xml \
		${gatein_modules}org/jboss/as/web/main/
		
		
	#next time skip build process
	date +%s > gatein_built_marker
fi

function validate_marker {
	#TODO - remove gatein_built_marker file if older than 24h
	#think about case if user redeploys app in 24h before we roll out updates
	#check for local system jboss AS version to force update
	
}
